[colors.bright]
black = "#808080"
blue = "#0066ff"
cyan = "#00ffff"
green = "#00d900"
magenta = "#cc00ff"
red = "#fe0100"
white = "#FFFFFF"
yellow = "#feff00"

[colors.cursor]
cursor = "#ffffff"
text = "#F81CE5"

[colors.normal]
black = "#000000"
blue = "#0066ff"
cyan = "#00ffff"
green = "#00a600"
magenta = "#cc00ff"
red = "#fe0100"
white = "#d0d0d0"
yellow = "#feff00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 13

[font.normal]
family = "MesloLGS Nerd Font"

[terminal]

[terminal.shell]
program = "/opt/homebrew/bin/fish"
